import type { Metadata } from "next";
import { Outfit, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { FaServer } from "react-icons/fa";
import Clock from "./Clock";

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  display: 'swap',
})

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${jetbrainsMono.variable} font-sans h-full antialiased bg-zinc-950`}
    >
      <body
        className="max-w-3xl w-full mx-auto text-white"
      >
        <div
          className="flex items-center text-zinc-500 border-b-1 border-white/10 py-7 font-mono text-sm"
        >
          <div className="flex items-center gap-2">
            <FaServer />
            <p>Example Org</p>
          </div>
          <div className="ml-auto">
            <Clock />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
